// <auto-generated />
using System;
using InfotecsTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfotecsTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830112720_FixONeToOne")]
    partial class FixONeToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("Report_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Report_Id");

                    b.ToTable("BaseMeasurement");

                    b.HasDiscriminator().HasValue("BaseMeasurement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.HasKey("Id");

                    b.ToTable("BaseReport");

                    b.HasDiscriminator().HasValue("BaseReport");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("Report_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Report_Id")
                        .IsUnique();

                    b.ToTable("BaseResult");

                    b.HasDiscriminator().HasValue("BaseResult");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InfotecsTest.Model.Value", b =>
                {
                    b.HasBaseType("InfotecsTest.Model.Abstract.BaseMeasurement");

                    b.Property<double>("Data")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval");

                    b.HasDiscriminator().HasValue("Value");
                });

            modelBuilder.Entity("InfotecsTest.Model.ValuesReport", b =>
                {
                    b.HasBaseType("InfotecsTest.Model.Abstract.BaseReport");

                    b.HasDiscriminator().HasValue("ValuesReport");
                });

            modelBuilder.Entity("InfotecsTest.Model.ValuesResult", b =>
                {
                    b.HasBaseType("InfotecsTest.Model.Abstract.BaseResult");

                    b.Property<TimeSpan>("AverageExicutionTime")
                        .HasColumnType("interval");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValie")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("ValuesResult");
                });

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseMeasurement", b =>
                {
                    b.HasOne("InfotecsTest.Model.Abstract.BaseReport", "Report")
                        .WithMany("Measurements")
                        .HasForeignKey("Report_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseResult", b =>
                {
                    b.HasOne("InfotecsTest.Model.Abstract.BaseReport", "Report")
                        .WithOne("Result")
                        .HasForeignKey("InfotecsTest.Model.Abstract.BaseResult", "Report_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("InfotecsTest.Model.Abstract.BaseReport", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
