// <auto-generated />
using System;
using InfotecsTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfotecsTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829045108_AbstractResult")]
    partial class AbstractResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfotecsTest.Model.BaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("Report_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Report_Id");

                    b.ToTable("BaseResult");

                    b.HasDiscriminator().HasValue("BaseResult");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InfotecsTest.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Resutl_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Resutl_Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("InfotecsTest.Model.Value", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Data")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("Report_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Report_Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("InfotecsTest.Model.Result", b =>
                {
                    b.HasBaseType("InfotecsTest.Model.BaseResult");

                    b.Property<TimeSpan>("AverageExicutionTime")
                        .HasColumnType("interval");

                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MedianValie")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Result");
                });

            modelBuilder.Entity("InfotecsTest.Model.BaseResult", b =>
                {
                    b.HasOne("InfotecsTest.Model.Report", "Report")
                        .WithMany()
                        .HasForeignKey("Report_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("InfotecsTest.Model.Report", b =>
                {
                    b.HasOne("InfotecsTest.Model.BaseResult", "Result")
                        .WithMany()
                        .HasForeignKey("Resutl_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("InfotecsTest.Model.Value", b =>
                {
                    b.HasOne("InfotecsTest.Model.Report", "Report")
                        .WithMany("Values")
                        .HasForeignKey("Report_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("InfotecsTest.Model.Report", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
